<?php

$mood_names_eng = array(
    'D'=>'Joyful',
    'Ab'=>'Stable',
    'C'=>'Melancholic'
);

$keywords_eng = array(
    "Fan",
    "Hope",
    "Carefreeness",
    "Daydreaming",
    "Drugs",
    "Letting go",
    "Joy",
    "Seriousness",
    "Freedom",
    "Energy",
    "Mockery",
    "Lightness",
    "Food",
    "Sportiness",
    "Doodle",
    "Rock'n'roll",
    "Accumulation",
    "Disorder",
    "Intoxication",
    "Ugliness",
    "Clownishness",
    "Addiction",
    "Star",
    "Twist",
    "Flavor",
    "Painting",
    "Gadgets",
    "Observation",
    "Furniture",
    "Stressed",
    "Gift",
    "Cheerfulness",
    "Annoyance",
    "Popstar",
    "Tidyng",
    "Limits",
    "Addiction",
    "Manipulation",
    "Thoughts",
    "Chaos",
    "Addiction",
    "Spaces",
    "Possibilities",
    "Pub",
    "Controversy",
    "Bazaar",
    "Nerdy",
    "Disagreement",
    "Imagination",
    "Beverage",
    "Liquor",
    "Unfinished",
    "Sparkle",
    "Indecisive",
    "Futility",
    "Savings",
    "Identity",
    "Adventure",
    "Uninhibited",
    "Harmony",
    "Cinephile",
    "Dissatisfaction",
    "Laziness",
    "Melody",
    "Dissonance",
    "Place",
    "Daily",
    "Symphony",
    "Swissness",
    "Taste",
    "Hits",
    "Ego",
    "Sewing",
    "Naivety",
    "Things",
    "Messy",
    "Celebrity",
    "Mask",
    "Computer",
    "Fed up",
    "Unhappy",
    "Instruments",
    "Dreamer",
    "Molecule",
    "Worries",
    "Useless",
    "Battle",
    "Liberation",
    "Out of tune",
    "Design",
    "Enthusiasm",
    "Gastronomy",
    "Intellect",
    "Spleen",
    "Beginnings",
    "Chaos",
    "Monotony",
    "Resignation",
    "Paradox",
    "Triumph",
    "Cigarette",
    "Admiration",
    "Blur",
    "Kitchen",
    "Works",
    "Trinkets",
    "Witness",
    "Distressing",
    "Stress",
    "Movie",
    "Prodigy",
    "Enough",
    "Me",
    "Order",
    "Casualness",
    "Addicted",
    "Sheep",
    "Lost",
    "Clutter",
    "Sport",
    "Ball",
    "Intrigued",
    "Destiny",
    "Melancholy",
    "Debates",
    "Confused",
    "Ugly",
    "Squabble",
    "Thoughts",
    "Drink",
    "Delight",
    "Incomplete",
    "Carefreeness",
    "Comments",
    "Hesitation",
    "Frivolity",
    "Chaos",
    "Identity",
    "Delirium",
    "Torments",
    "Organized",
    "Movies",
    "Fragile",
    "Duvet",
    "Tuning",
    "Lightness",
    "Car",
    "Fame",
    "Roots",
    "Melancholy",
    "Controversy",
    "Computer",
    "Boredom",
    "Illusion",
    "Brussels",
    "Villain",
    "Celebrity",
    "Fate",
    "Appetite",
    "Forbidden",
    "Limit",
    "Travel",
    "Car",
    "Mess",
    "Night",
    "Disappearance",
    "Red",
    "Buried",
    "Abandonment",
    "Idol",
    "Fed up",
    "Dream",
    "Lightness",
    "Voice",
    "Instruments",
    "Original",
    "Happiness",
    "Addiction",
    "Worries",
    "Disappointment",
    "Offbeat",
    "Wacky",
    "Deliberate",
    "Nonconformist",
    "Tinted",
    "Madness",
    "Joy",
    "Offense",
    "Ingredients",
    "Recipe",
    "Athletic",
    "Mental",
    "Writing",
    "Satisfaction",
    "Drums",
    "Pride",
    "Heap",
    "Treasures",
    "Mess",
    "Chaos",
    "Meaning",
    "Ugly",
    "Hits",
    "Success",
    "Tobacco",
    "Smoke",
    "Dassin",
    "Fan",
    "Oddity",
    "Béchamel",
    "Cooking",
    "Zucchini",
    "Creativity",
    "Accessible",
    "Stuff",
    "Ustensils",
    "Knick-knacks",
    "People",
    "Fast-Food",
    "Fear",
    "Clumsiness",
    "Clues",
    "Superpower",
    "Details",
    "Wacky",
    "Fun",
    "Nausea",
    "King",
    "Adventures",
    "Imaginary",
    "Jumble",
    "Freedom",
    "Connected",
    "Tech-addict",
    "Naive",
    "Gullible",
    "Flop",
    "Comic",
    "Upheaval",
    "Mess",
    "Adrenaline",
    "Burst",
    "Fascination",
    "Choice",
    "Walk",
    "Pub",
    "Jokes",
    "Mess",
    "Flashy",
    "Opinions",
    "Stubborn",
    "Flashes",
    "Spontaneity",
    "Infusion",
    "Revival",
    "Beverage",
    "Liquor",
    "Reading",
    "Calvary",
    "Celebration",
    "Positivity",
    "Ambiguity",
    "Insignificance",
    "Trivial",
    "Me",
    "Fantasy",
    "Crazy",
    "Interior",
    "Marginal",
    "Clutter",
    "Imperfect",
    "Passion",
    "Hollywood",
    "Genius",
    "Lazybones",
    "Cacophony",
    "Smile",
    "Magic",
    "Story",
    "Story",
    "Normal",
    "Computer",
    "Division",
    "Blur",
    "Brussels",
    "Post",
    "Keyboard",
    "Asshole",
    "Puzzle",
    "Hit",
    "Helvetia",
    "Instrument",
    "Look",
    "Funny",
    "Crazy",
    "Idleness",
    "Limits"
);

$titles_eng = array(
    "My Idol",
    "Just Believd",
    "Childish pleasure",
    "Looking up",
    "Dopamine machines",
    "It's not a big deal, as long as we're having fun",
    "What matters is laughing",
    "Mix in my head",
    "My faithful friend",
    "Energetic mode",
    "Question of intention",
    "Laughing is better",
    "My little kitchen",
    "The winning mind",
    "Writing is my pleasure",
    "Rock Star",
    "The crazy collection",
    "The mess in my head",
    "The world of little ironies",
    "Ugly beauty",
    "Popular and funny",
    "Cigarette",
    "Joe Dassin",
    "Double meaning",
    "Veggie lasagna, my madness",
    "Art for all",
    "Object Mania",
    "People",
    "At Casa's",
    "Stage fright",
    "My visual memory",
    "Just for laughs",
    "I don't like clowns",
    "An eccentric pop star",
    "Wacky scenarios",
    "No limits",
    "Addicted to my phone",
    "I let myself be convinced",
    "A Delirious world",
    "Living in chaos",
    "I'm addicted",
    "In public places",
    "Play with your choices",
    "At the local bistro",
    "Vain controversy",
    "A joyful mess",
    "The incarnation of bad taste",
    "I like arguments",
    "Reflex ideas",
    "Tea that plays tricks",
    "Ginger Gérard",
    "Abandoned novels",
    "Long live positivity",
    "Sometimes I have no opinion",
    "Frivolous life",
    "Cheap galore",
    "Hey my friend",
    "The crazy adventure of my head",
    "In life you have to own it",
    "I'm messy",
    "Cinema is a party",
    "It's a bit easy",
    "The lazy attitude",
    "A song Without reason",
    "I sing out of tune",
    "Clear the space",
    "Crazy in the ordinary",
    "I don't need notes",
    "The Swiss artist",
    "Bad taste",
    "The Hit Machine",
    "The Theater of me",
    "The seams",
    "Light song",
    "My reality",
    "My mess",
    "Am I me",
    "A nice guy",
    "A mysterious dance",
    "Overdose",
    "The Blues",
    "Without Instrument",
    "Eyes in the Void",
    "Dopamine Addiction",
    "It's not a big deal, but it's a shame",
    "Mediocrity",
    "Context story",
    "Freedom",
    "What's your tone?",
    "I didn't do it on purpose",
    "Not in a bad mood",
    "The recipe for the party",
    "The brain champion",
    "Melo-choly",
    "The drum",
    "My joyful mess",
    "The wrong order",
    "The funny singer",
    "Ugly things",
    "My only prayer",
    "I'm addicted",
    "I like Joe Dassin",
    "Ambiguity",
    "Vegetarian lasagna",
    "Art for dummies",
    "Love of objects",
    "Dancing with glances",
    "People at Casa's",
    "Stage fright",
    "Visual memory",
    "No need for virtuosity",
    "Stop the clowns",
    "Hidden under the seams",
    "Hollywood-style tidying",
    "The big jump",
    "Slave to my phone",
    "I'm the pigeon of opinions",
    "In a sad mood",
    "The walking mess",
    "Squash game",
    "I like playing squash",
    "The passers-by's ball",
    "Go with the flow",
    "An evening at the bistro",
    "The controversy",
    "The disorder",
    "Bad taste",
    "Nobody cares",
    "Reflex ideas",
    "Tea, an ignored pleasure",
    "Ginger liqueur",
    "Unfinished books",
    "No commitment required",
    "Critics",
    "Life in indecision",
    "The world of futility",
    "Don't try to understand",
    "Who am I really?",
    "Lost in my head",
    "Let's forget the sorrows",
    "The messy paradox",
    "Cinema Passion",
    "Too easy",
    "Life in pajamas",
    "The wrong note",
    "A not so sad song",
    "Goodbye my old electric",
    "Beyond the lights",
    "Uprooted",
    "Sweet Sadness",
    "Melancholic distance",
    "The enigma of computing",
    "The sleeping city",
    "THE BALL OF ILLUSIONS",
    "The chaos of Brussels",
    "The mask of the nice guy",
    "The price of success",
    "PARALLEL PATHS",
    "Restaurants",
    "Forbidden feelings",
    "The limit zones",
    "My Beautiful Electric Car",
    "My Little Red Car",
    "My own mess",
    "Normal",
    "Where are you?",
    "Running the red light",
    "A complicated love",
    "Sleeping City",
    "My muse",
    "Overdose",
    "I'm not crazy, I believe in it",
    "Without believing",
    "Make you dance",
    "A lazy singer",
    "Unique style",
    "Dopamine Party",
    "The Dopamine Dance",
    "It's a shame, but it's not a big deal",
    "It doesn't matter if it sucks",
    "Context story",
    "The crazy context",
    "A rule to follow",
    "My credo",
    "What is your tone?",
    "Question of intention",
    "Sincere smile",
    "A crazy world",
    "Cooking Passion",
    "Cook me happiness",
    "Invincible",
    "You're the champion",
    "Notebooks",
    "The magic of notebooks",
    "The plastic drum",
    "The drum king",
    "The crazy collection",
    "The collector",
    "Long live disorder!",
    "Mess it up!",
    "Carefree",
    "Outdated things",
    "Pop addiction",
    "Superstar",
    "Delicious smoke",
    "The puff party",
    "Joe fan",
    "My providence",
    "Ambiguity is my credo",
    "Crazy lasagna",
    "Lasagna is my pride",
    "Vegetarian lasagna",
    "Art madness",
    "Art for all",
    "Object mania",
    "I love objects",
    "In my drawers",
    "Everyone is unique",
    "Stop hipster meals",
    "Stage fright",
    "I have stage fright",
    "Lynx eye",
    "My visual memory",
    "In my head",
    "My little madness",
    "We are rockstars",
    "I hate clowns",
    "Couture show",
    "In my life, everything is a movie",
    "The starry mess",
    "The mess is my instinct",
    "No limit",
    "I am addicted to my phone",
    "Phone mania",
    "I stick to everyone",
    "Easily convinced",
    "I am not on top",
    "The little things in life",
    "Long live the mess",
    "Mess is life",
    "Squash rocks!",
    "Swing your squash",
    "The magic of public places",
    "Always indecisive",
    "According to desires",
    "This charming bistro",
    "I'm kidding!",
    "The disorder tells something",
    "Kitsch is chic",
    "The mishmash of opinions",
    "All opinions",
    "The race of ideas",
    "Reflexes gone wide",
    "Tea rocks my palate",
    "Tea, my favorite ally",
    "Ginger lover",
    "Ginger bling bling",
    "The unfinished adventure",
    "Finish the books",
    "Long live the party without commitment",
    "No worries, only smiles",
    "Artistic blur",
    "The world of futility",
    "Cheap, cheap, cheap",
    "My madness, my greatest asset",
    "Crazy thoughts",
    "Lost in my bubble",
    "In my bubble",
    "Crazy",
    "Organized chaos",
    "The perfect mess",
    "The Cinephile",
    "Cinemania",
    "Too easy",
    "Laziness is my credo",
    "Musical imposter",
    "A song without reason",
    "The master of laughter",
    "A funny story",
    "A story that blows your mind",
    "Balance",
    "Magical computing",
    "Lightness in song",
    "Life in disorder",
    "My mess my happiness",
    "Post Packages",
    "Hands on the keyboard",
    "Nice guy",
    "My happy mess",
    "A crazy story",
    "The Swiss artist",
    "Song without instrument",
    "Distant look",
    "The funny artist",
    "Ordinary",
    "Lazy but healthy",
    "Adventure awaits us"
);