<?php

$keywords_eng = array(
    "Fan",
    "Hope",
    "Carefreeness",
    "Daydreaming",
    "Drugs",
    "Letting go",
    "Joy",
    "Seriousness",
    "Freedom",
    "Energy",
    "Mockery",
    "Lightness",
    "Food",
    "Sportiness",
    "Scribble",
    "Rock'n'roll",
    "Accumulation",
    "Disorder",
    "Drunkenness",
    "Ugliness",
    "Clowniness",
    "Addiction",
    "Star",
    "Twist",
    "Flavor",
    "Painting",
    "Gadgets",
    "Observation",
    "Furniture",
    "Stressed",
    "Gift",
    "Joyfulness",
    "Annoyance",
    "Seams",
    "Storage",
    "Dice sinvolte",
    "Addiction",
    "Manipulation",
    "Thoughts",
    "Boudel",
    "Fun",
    "Spaces",
    "Possibilities",
    "Troquet",
    "Quarrels",
    "Bazaar",
    "Nerdy",
    "Disagreement",
    "Imagination",
    "Drink",
    "Liquor",
    "Unfinished",
    "Brightness",
    "Indecisive",
    "Futility",
    "Economies",
    "Identity",
    "Perched",
    "Uninhibited",
    "Harmony",
    "Cinephile",
    "Dissatisfaction",
    "Laziness",
    "Melody",
    "Dissonance",
    "Place",
    "Daily",
    "Symphony",
    "Swissness",
    "Go ût",
    "Tubes",
    "Ego",
    "Couture",
    "Naivety",
    "Things",
    "Bordel",
    "Celebrity",
    "Mask",
    "Computer",
    "Fed up",
    "Unhappy",
    "Instruments",
    "Dreamer",
    "Molecule",
    "Worries",
    "Zero",
    "Battle",
    "Liberation",
    "Out of tune",
    "Design",
    "Enthusiasm",
    "Gastronomy",
    "Intellect",
    "Spleen",
    "Beginnings",
    "Chaos",
    "Monotony",
    "Resignation",
    "Paradox",
    "Triumph",
    "Cigarette",
    "Admiration",
    "Blur",
    "Cuisine",
    "Works",
    "Trinkets",
    "T witness",
    "Distressing",
    "Stress",
    "Movie",
    "Prodigy",
    "Enough",
    "Me",
    "Order",
    "Casuality",
    "Addicted",
    "Sheep",
    "Lost",
    "Clutter",
    "Sport",
    "Ball",
    "Intrigued",
    "Destiny",
    "Melancholy",
    "Debates",
    "Confused",
    "Ugly",
    "Bickering",
    "Thoughts",
    "Drink",
    "Delight",
    "Incomplete",
    "Carelessness",
    "Comments",
    "Hesitation",
    "Frivolity",
    "Chaos",
    "Identity",
    "Delusions",
    "Torments",
    "Organized",
    "Movies",
    "Fragile",
    "Duvet",
    "Case serole",
    "Lightness",
    "Car",
    "Fame",
    "Roots",
    "Melancholy",
    "Controversy",
    "Computer",
    "Boredom",
    "Illusion",
    "Brussels",
    "Villain",
    "Celebrity",
    "Destiny",
    "Appetite",
    "Forbidden",
    "Limit",
    "Travel",
    "Boilde",
    "Bordel",
    "Night",
    "Disappearance",
    "Red",
    "Buried",
    "Abandonment",
    "Idol",
    "Fed up",
    "Dream",
    "Lightness",
    "Voice",
    "Instruments",
    "Original",
    "Happiness",
    "Addiction",
    "Worries",
    "Disappointment",
    "Offbeat",
    "Crazy",
    "Deliberate",
    "Ant iconformist",
    "Tinted",
    "Madness",
    "Joy",
    "Offense",
    "Ingredients",
    "Recipe",
    "Sporty",
    "Mental",
    "Writing",
    "Satisfaction",
    "Drums",
    "Pride",
    "Heaps",
    "Treasures",
    "Bazaar",
    "Chaos",
    "Meaning",
    "Ugly",
    "Tubes",
    "Success",
    "Tobacco",
    "Smoke",
    "Dassin",
    "Fan",
    "Oddity",
    "Béchamel",
    "Cooking",
    "Zucchini",
    "Creativity",
    "Accessible",
    "Tricks",
    "Utensils",
    "Gizmos",
    "People",
    "Fast-Food",
    "Fear",
    "Clumsiness",
    "Clues",
    "Supe r-power",
    "Details",
    "Wacky",
    "Fun",
    "Nausea",
    "King",
    "Adventures",
    "Imaginary",
    "Jumble",
    "Freedom",
    "Connected",
    "Tech-addict",
    "Naive",
    "Gullible",
    "Flop",
    "Comic",
    "Upheaval",
    "Cheni",
    "Adrenaline",
    "Burst",
    "Fascination",
    "Choice",
    "Walk",
    "Troquet",
    "Jokes",
    "Mess",
    "Flashy",
    "Din",
    "Stubborn",
    "Flashes",
    "Spontaneity",
    "Infusion",
    "Revival",
    "Beverage",
    "Liqueur",
    "Reading",
    "Calvary",
    "Cé lebration",
    "Positivity",
    "Ambiguity",
    "Insignificance",
    "Trivial",
    "Me",
    "Fantasy",
    "Crazy",
    "Inner",
    "Marginal",
    "Chafarnaüm",
    "Imperfect",
    "Passion",
    "Hollywood",
    "Genius",
    "Lazy",
    "Cacophony",
    "Smile",
    "Magic",
    "Story",
    "Story",
    "Normal",
    "Computer",
    "Division",
    "Blur",
    "Brussels",
    "Post",
    "Keyboard",
    "Asshole",
    "Puzzle",
    "Tube",
    "Helvetia",
    "Instrument",
    "Look",
    "Funny",
    "Crazy",
    "Idleness",
    "Limits"
);

$titles_eng = array(
    "Titre EN",
    "My Idol",
    "Just believe it",
    "A childish pleasure",
    "Looking up in the air",
    "Dopamine machines",
    "It doesn't matter, as long as we're having fun",
    "What matters is laughing",
    "Mixing in my head",
    "My faithful friend",
    "In tonic mode",
    "Question of intention",
    "Laughing is better",
    "My little kitchen",
    "The winning mind",
    "Writing is my pleasure",
    "Rock Star",
    "The crazy collection",
    "The mess in my head",
    "The world of little ironies",
    "Ugly beauty",
    "Popular and funny",
    "Cigarette",
    "Joe Dassin",
    "Double meaning",
    "Veggie lasagna, my madness",
    "Art for all",
    "Objectmania",
    "People",
    "At Casa",
    "Stage fright",
    "My visual memory",
    "Just for laughs",
    "I don't like clowns",
    "An eccentric pop star",
    "Wacky scenarios",
    "Without limits",
    "Addicted to my phone",
    "I let myself be convinced",
    "A crazy world",
    "Living in the chaos",
    "Squash",
    "In public places",
    "Play with your choices",
    "At the local bistro",
    "Political vein",
    "A joyful mess",
    "The embodiment of bad taste",
    "I like arguments",
    "Reflex ideas",
    "Tea that plays tricks",
    "Ginger Gérard",
    "Abandoned novels",
    "Long live positivity",
    "Sometimes I have no opinion",
    "Frivolous life",
    "Cheap galore",
    "Hey my friend",
    "The crazy adventure of my head",
    "In life you have to assume yourself",
    "I'm messy",
    "Cinema is a party",
    "It's a bit easy",
    "The lazy attitude",
    "A song for no reason",
    "I sing out of tune",
    "Clear the space",
    "Crazy in the ordinary",
    "I don't need notes",
    "The Swiss artist",
    "Bad taste",
    "The Tube Machine",
    "The Theater of me",
    "The seams",
    "Light song",
    "My reality",
    "My mess",
    "Am I me",
    "A nice guy",
    "A mysterious dance",
    "Overdose",
    "Depression",
    "Without Instrument",
    "Eyes in the Wave",
    "Dopamine Addiction",
    "No big deal, but it's a shame",
    "Mediocrity",
    "Background story",
    "Freedom",
    "What's your tone?",
    "I didn't do it on purpose",
    "Not in a bad mood",
    "The party recipe",
    "The brain champion",
    "Melo-choly",
    "The drum",
    "My happy mess",
    "The bad order",
    "The funny singer",
    "Ugly things",
    "My only prayer",
    "I'm addicted",
    "I like Joe Dassin",
    "Ambiguity",
    "Vegetarian lasagna",
    "Art for dummies",
    "Love of objects",
    "Dancing with looks",
    "People at Casa",
    "Stage fright",
    "Visual memory",
    "No need for virtuosity",
    "Stop the clowns",
    "Hidden under the seams",
    "Hollywood-style tidying",
    "The big jump",
    "Slave to my phone",
    "I'm the pigeon of opinions",
    "In a sad mood",
    "The walking mess",
    "Squash game",
    "I like playing squash",
    "The passers-by's ball",
    "Letting yourself be carried away by life",
    "One evening at the bistro",
    "The controversy",
    "The disorder",
    "Bad taste",
    "Nobody cares",
    "Reflex ideas",
    "Tea, a pleasure ignored",
    "Ginger liqueur",
    "Unfinished books",
    "No obligation to commit",
    "Critics",
    "Life in indecision",
    "The world of trivialities",
    "Don't try to understand",
    "Who am I really?",
    "Lost in my head",
    "Let's forget the sorrows",
    "The messy paradox",
    "Passionate cinema",
    "Too easy",
    "Life in pajamas",
    "The wrong note",
    "A song not so sad",
    "Goodbye my old electric",
    "Beyond the lights",
    "Uprooted",
    "Sweet Sadness",
    "Melancholic distance",
    "The enigma of computing",
    "The sleeping city",
    "THE BALL OF ILLUSIONS",
    "The chaos of Brussels",
    "The mask of the nice guy",
    "The price of success",
    "PARALLEL PATHS",
    "Restaurants",
    "Forbidden feelings",
    "The limit zones",
    "My Beautiful Electric Car",
    "My Little Red Racing Car",
    "My own mess",
    "Normal",
    "Where are you?",
    "Going red",
    "A complicit love",
    "Sleeping City",
    "My muse",
    "Overdose",
    "I'm not crazy, I believe in it",
    "Without believing it",
    "Make you dance",
    "A lazy singer",
    "Singular style",
    "Dopamine Party",
    "The dance of dopamine",
    "It's too bad but it doesn't matter",
    "It doesn't matter if it sucks",
    "A story of context",
    "The crazy context",
    "A rule to follow",
    "My credo",
    "What is your tone?",
    "Question of intention",
    "Sincere smile",
    "A crazy world",
    "Passion for cooking",
    "Cook me happiness",
    "Invincible",
    "You're the champion",
    "Notepads",
    "The magic of notepads",
    "The plastic drum",
    "The king of the drum",
    "The crazy collection",
    "The collector",
    "Long live disorder!",
    "Create a mess!",
    "No-brainer",
    "Outdated things",
    "Pop addiction",
    "Superstar",
    "Delicious smoke",
    "The puff party",
    "Joe fan",
    "My providence",
    "Ambiguity is my credo",
    "Crazy lasagnas",
    "Lasagnas are my pride",
    "Vegetarian lasagnas",
    "Art madness",
    "Art for all",
    "Objetmania",
    "I love objects",
    "In my drawers",
    "Everyone is unique",
    "Stop hipster meals",
    "Stage fright",
    "I have stage fright",
    "Eye of a lynx",
    "My visual memory",
    "In my head",
    "My little madness",
    "We are rock stars",
    "I hate clowns",
    "Couture show",
    "In my life, everything is a movie",
    "The bazaar of stars",
    "The bazaar is my instinct",
    "Without limits",
    "I am addicted to my phone",
    "Telephone-mania",
    "I get hooked on everyone",
    "Easily convinced",
    "I am not at the top",
    "The little things in life",
    "Long live the mess",
    "The damn, that's life",
    "Squash rocks!",
    "Swing your squash",
    "The magic of public places",
    "Always undecided",
    "According to the mood",
    "This charming bistro",
    "I'm kidding!",
    "The disorder tells something",
    "Kitsch is chic",
    "The bric-a-brac of opinions",
    "All opinions",
    "The race of ideas",
    "Crazy reflexes",
    "Tea tears my palate apart",
    "Tea, my favorite ally",
    "Ginger lover",
    "Gling gling ginger",
    "The unfinished adventure",
    "Finish the books",
    "Long live the party without commitment",
    "No worries, only smiles",
    "Artistic blur",
    "The world of trivia",
    "Cheap, cheap, cheap",
    "My madness, my greatest asset",
    "Wacky thoughts",
    "Lost in my bubble",
    "In my bubble",
    "Crazy",
    "Organized chaos",
    "The perfect mess",
    "The movie buff",
    "Cinemania",
    "Too easy",
    "Laziness is my credo",
    "Musical imposter",
    "A song without reason",
    "The master of laughter",
    "A funny story",
    "A short story that rocks",
    "Balance",
    "Magical computing",
    "Lightness in song",
    "Life in disorder",
    "My mess my happiness",
    "Parcels from the post office",
    "Hands on the keyboard",
    "Nice guy",
    "My happy mess",
    "A crazy story",
    "The Swiss artist",
    "Song without instrument",
    "Distant look",
    "The funny artist",
    "Banal",
    "Lazy but healthy",
    "Adventure awaits us"
);